
server:
  port: 8080
  servlet:
    context-path: /

spring:
  thymeleaf:
    cache: false #关闭thymeleaf缓存，有利于开发阶段的调试
    prefix: classpath:/templates/ #指定页面的存放位置（默认）
    suffix: .html #指定页面的后缀（默认）
    encoding: utf-8
    mode: LEGACYHTML5
    servlet:
      content-type: text/html


  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/bookshop?serverTimezone=UTC
   username: root
   password: 1234
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

#  mvc:
#    static-path-pattern: /images/**
    #使用了此方式后，默认静态访问路径会失效，默认路径如下
    #classpath:/META-INF/resources/,
    #classpath:/resources/,
    #classpath:/static/,
    #classpath:/public/
#  web:
#    resources:
#      static-locations: file:D:\20191113227dazuoye\src\main\resources\static\images

#  mvc:
#    static-path-pattern: /**

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D:\20191113227dazuoye\src\main\resources\static\images,classpath:/public/


#  web:
#    resources:
#      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D:\20191113227dazuoye\src\main\resources\static\images


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: sspu.informationsystem.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    sspu.informationsystem: debug
    sspu.informationsystem.mapper: debug
